- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Fetch the latest version of application code
      ansible.builtin.git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith # <-- Указываем нужную ветку
      notify: Restart puma

    - name: Bundle install
      ansible.builtin.bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers: # <-- Добавим блок handlers и задачу
    - name: Restart puma
      ansible.builtin.service:
        name: puma
        state: restarted
